version: '3.7'

services:
  backend:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: flask
    image: flask-python:3.8
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "True"
      APP_PORT: 5000
      MONGODB_DATABASE: flaskdb
      MONGODB_USERNAME: flask
      MONGODB_PASSWORD: your_mongodb_password
      MONGODB_HOSTNAME: mongodb
      JWT_SECRET_KEY: 'OtVq4af0aNGQeGa6802e6MXnIGPINt43'
    volumes:
      - ./app:/var/www
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: your_mongodb_root_password
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
